Cart Entity
piotr-grosicki/project-jdp-2211-01 pull request #11
Opened 2022-10-25 18:58 UTC by pawelkrzywda

2022-10-26 06:34 UTC, piotr-grosicki requested changes
projekt sie nie buduje + konflikty

2022-10-26 21:05 UTC, piotr-grosicki submitted a review, later dismissed
konflikty

2022-10-28 10:18 UTC, Coriv requested changes
1. Relacja z encją User to relacja ManyToOne (jeden klient może mieć wiele różnych koszyków)
2. Brakuje relacji OneToOne z encją Order
3. Przy JoinTable robimy relacje ManyToMany (stad potrzebna nam dodatkowa tabela zapisująca te powiązania) 
4. Stworzyłeś gdzieś kontroler repozytorium CartDao? To chyba tez była część zadania

2022-10-29 20:56 UTC, Damian1457 approved these changes

2022-10-31 08:19 UTC, Damian1457 approved these changes

2022-11-01 18:32 UTC, Coriv approved these changes
Wyglada ok

2022-11-01 18:33 UTC, merged