implementation product entity
piotr-grosicki/project-jdp-2211-01 pull request #19
Opened 2022-10-31 11:01 UTC by shinzu94

2022-11-01 12:08 UTC, Damian1457 reviewed
Jak dla mnie wszystko gra.

2022-11-01 18:03 UTC, Coriv requested changes
Brakuje relacji ManyToMany z encją Cart,
Paweł już w swoim commicie opisał te relacje z jednej strony (link poniżej), więc można by to dograć od razu. 

https://github.com/piotr-grosicki/project-jdp-2211-01/pull/11/files

2022-11-02 11:05 UTC, shinzu94 commented
Co prawda relacja dwukierunkowa nie była niezbędna, prawdopodobnie jest nawet zbędna, no ale dla spokuju twojego sumienia zmieniłem
> Brakuje relacji ManyToMany z encją Cart, Paweł już w swoim commicie opisał te relacje z jednej strony (link poniżej), więc można by to dograć od razu.
> 
> https://github.com/piotr-grosicki/project-jdp-2211-01/pull/11/files

2022-11-02 15:57 UTC, Coriv approved these changes

2022-11-02 19:55 UTC, Damian1457 approved these changes

2022-11-02 19:56 UTC, merged