ProductController real imlementation
piotr-grosicki/project-jdp-2211-01 pull request #20
Opened 2022-10-31 16:55 UTC by Coriv

2022-11-02 17:54 UTC, shinzu94 requested changes
Możesz użyć reformat code

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +public class ProductDbService {
Ta klasa moim zdaniem powinna nazywać się ProductService

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        return product;
Nie musisz deklarować zmiennej skoro i tak odrazu wszystkie parametery w kontrktorze podajesz.
Choć czytelniej by było użyć setererów

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        return productDto;
Ta metoda nie za bardzo mapuje

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +    public List<Product> mapToProductsList(List<ProductDto> productDtoList) {
Deklarujesz nie używaną funkcje które na ten moment nie ma szansy być używana nawet w następnych taskach

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                .map(n -> mapToProductDto(n))
Jeśli już robić maper całej listy to w tej linijce było by lepsze wywołanie statyczne
``.map(this::mapToProductDto)``

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +package com.kodilla.ecommercee.domain;
Masz starego product którego i tak musimy wyjaśnić :D

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ResponseEntity<ProductDto> deleteProduct(@PathVariable Long productId) throws ProductNotFoundException{
Przy deletach nie zwykło się zwracać starej encji

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    @Autowired
`@Autowired` uznawane jest za antypatern i stosuje się konstruktor

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    ProductDbService dbService;
nie ma modyfikatora dostępu

2022-11-02 17:54 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    ProductMapper mapper;
nie ma modyfikatora dostępu

2022-11-02 19:59 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +package com.kodilla.ecommercee.domain;
Widzę, że właśnie została dodana nowa wersja Product do maina, trzeba by porównać te dwa pliki.

2022-11-02 20:07 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/repository/ProductDao.java
> +    List<Product> findAll();
Przy tych deklaracjach metod powinna być adnotacja @Override.

2022-11-02 20:09 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/service/ProductDbService.java
> +    ProductDao productDao;
brak modyfikatora dostępu

2022-11-02 20:13 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/repository/ProductDao.java
> +import com.kodilla.ecommercee.domain.Product;
Product powinien być importowany z pakietu entities

2022-11-02 20:19 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +import com.kodilla.ecommercee.domain.Product;
Import Product powinien być z pakietu entities, podobnie w klasach ProductMapper, ProductDao, ProductDbService

2022-11-02 20:22 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ResponseEntity<ProductDto> updateTask(@RequestBody ProductDto productDto) throws ProductNotFoundException {
Nazwa metody do zmiany, chyba to ja taką dałem w pierwszej wersji pliku :)

2022-11-04 19:17 UTC, pawelkrzywda commented
Wygląda ok, jedynie konflikty są do rozwiązania.

2022-11-06 00:23 UTC, shinzu94 requested changes
Jeśli dobrze widzę.
1. Masz dodane Group i Prodct ręcznie. Jeśli tak to warto je wywalić i zrobić merge z mastera
2. Kwestiaużtcia buildera dla ProducctDto
3. I pozostał komentarz z mapera dotyczący wywołania statycznego

2022-11-06 19:22 UTC, shinzu94 approved these changes

2022-11-06 19:25 UTC, merged