Jdp221101 25 user controller implementation
piotr-grosicki/project-jdp-2211-01 pull request #21
Opened 2022-11-01 20:19 UTC by matnow138

2022-11-02 15:55 UTC, shinzu94 reviewed
Co prawda nie dodawałeś tego(przynajmniej w tym branchu) to nie stosuje się @Autowired tylko konstruktor

2022-11-02 16:06 UTC, shinzu94 reviewed
w UserController nie ma endpointów do aktualizacji i do wylistowania użtrkowników

2022-11-02 16:10 UTC, shinzu94 reviewed
Przydało by się zrobić reformat code

2022-11-02 16:10 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/globalErrorHandler/GlobalHttpErrorHandler.java
> +import com.kodilla.ecommercee.exception.OrderNotFoundException;
Nie używasz takiej klasy

2022-11-02 16:33 UTC, shinzu94 reviewed
Nie zrobiłeś UserService

2022-11-02 17:22 UTC, shinzu94 requested changes

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +               .setExpiration(new Date(now +3600))
3600 to 3,6 sekundy
https://jwt.io/ tutaj możesz sobie sprawdzić co taki token znaczy

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +               .setExpiration(new Date(now +3600))
Inna sprawa, ważność tokenu pasowała by do konfiga

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        User user = userDao.findById(userID).orElseThrow(UserNotFoundException::new);
Szukasz tylko użykownika, ale nie porównujesz hasła

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;
Lepiej stosować szyfrowanie eliptyczne(ES) i zwykle lepiej stosować więcej bitów(512) co daj `SignatureAlgorithm.ES512`

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;
Nie musisz tego szyfrowania tworzyć każdorazowo, bo zawsze jest takie samo. Więc możesz zrobić singletona(lub coś koło tego)

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        User user = userDao.findById(userID).orElseThrow(UserNotFoundException::new);
A tak w zasadzie to szukasz pi id a nie loginie :D

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        String SECRET_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2p3dC1pZHAuZXhhbXBsZS5jb20iLCJzdWIiOiJtYWlsdG86bWlrZUBleGFtcGxlLmNvbSIsIm5iZiI6MTY2NzE1NzIyOCwiZXhwIjoxNjY3MTYwO
Lepiej użyć generatora haseł
To też by się nadawało do konfigów

2022-11-02 17:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public String generateToken(@PathVariable long userID) throws UserNotFoundException {
W przypadku nie powiedzenia tego endpointu status powinien być 401 (Unauthorized)

2022-11-03 20:44 UTC, shinzu94 requested changes

2022-11-03 20:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public UserController(UserMapper userMapper, UserDao userDao) {
Ten konstruktor i @Autowired możesz zastąpić używająć lomboka
``
@AllArgsConstructor
albo
@RequiredArgsConstructor
``
tylko w drugim wypadku musisz dodać final 
`
    private final UserMapper userMapper;
    private final UserDao userDao;
`
co bym zalecał :)

2022-11-03 20:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        User user = userDao.findByLogin(login).orElseThrow(UserNotFoundException::new);
Jak znajdzie użytkownika będzie inny błąd niż jak złe hasło co powoduje, że można się dowiedzieć, że użytkownik istnieje i teraz starczy hasło złamać

2022-11-03 20:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +                    .setSubject("userid") // 1
Tutaj musiałbyś włożyć albo id albo login

2022-11-03 20:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +            val keys = Keys.keyPairFor(SignatureAlgorithm.ES512);
staraj się nie używać val tylkow tym wypadku KeyPair

2022-11-03 20:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +                    .setIssuedAt(Date.from(Instant.now()))
Instant.now()  z tej linijki jest inynym Instant.now() z kolejnej... dla tego warto zapisać to do zmiennej i z nie skorzystać

2022-11-04 06:27 UTC, matnow138 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +            val keys = Keys.keyPairFor(SignatureAlgorithm.ES512);
Możesz wyjaśnić dlaczego? Czy var byłoby tutaj ok?

2022-11-04 19:11 UTC, pawelkrzywda reviewed
Drobny refaktor kodu by się przydał w ProductController - trochę zbędnych pustych linii.

2022-11-04 19:52 UTC, matnow138 commented
ProductController ściągnięty z maina - to nie jest mój plik.

2022-11-04 20:01 UTC, pawelkrzywda approved these changes

2022-11-06 00:33 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +            val keys = Keys.keyPairFor(SignatureAlgorithm.ES512);
@matnow138 jasne. Chodzi o to, że jak podasz typ to za tydzień jak spojrzysz w kod to będzie dla ciebie jasne co to jest.

2022-11-06 00:36 UTC, shinzu94 requested changes

2022-11-06 00:36 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<String> generateToken(@PathVariable String login, String password) {
A w jaki sposób w postmanie przyjmujesz tego passworda?

2022-11-06 19:53 UTC, shinzu94 requested changes
Wpadły konflikty z masterem więc musisz rozwiązać.

Tak pozatym jest dobrze tylko zauważyłem, że mógłbyś wrzucić 2 rzeczy do serwisu zamiast bezpośrenio w kontrolerze odpalać :+1:

2022-11-06 19:53 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +        }
Skoro i tak musisz rozwiązać konflikty to postaraj się to przenieść do serwisu zamiast controllera

2022-11-06 19:53 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
>          userDao.save(user);
Skoro i tak musisz rozwiązać konflikty to postaraj się to przenieść do serwisu zamiast controllera

2022-11-06 19:57 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PostMapping(value = "/generateToken")
Tylko widzę, że tu Post, a nie get jest :)

2022-11-06 20:02 UTC, matnow138 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PostMapping(value = "/generateToken")
Z tego co czytałem i rozmawiałem z innymi, przy GET nie powinno używać się body, a ja tutaj wymagam podania.

2022-11-07 11:59 UTC, Coriv approved these changes

2022-11-07 13:43 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PostMapping(value = "/generateToken")
Ale Post służy do tworzenia, security zawsze jest takim obszarem dla którego sie robi wyjątki, bo gdyby stosować się do ogólnych zasad apkikacja byłby dzurawe pod tym względem :+1:

2022-11-07 13:45 UTC, shinzu94 approved these changes

2022-11-07 13:46 UTC, merged