OrderController implementation
piotr-grosicki/project-jdp-2211-01 pull request #22
Opened 2022-11-02 20:32 UTC by Damian1457

2022-11-03 18:54 UTC, Damian1457 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return ResponseEntity.ok(orderMapper.mapToOrderDto(saveOrder));
Bo najpierw musisz utworzyć nowe zamówienie, później je zapisać, a dopiero później zwrócić.

2022-11-03 18:54 UTC, Damian1457 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public ResponseEntity<OrderDto> updateOrder(@RequestBody OrderDto orderDto) {
Nie

2022-11-03 19:56 UTC, shinzu94 requested changes

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public ResponseEntity<Void> createOrder(@RequestBody OrderDto orderDto) {
jeśli przy update coś zwracasz to tym bardziej przy create

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +@Builder
W kontrollerach nie potrzebujesdz buildara, bo nigdy nie będziesz składał tego ręcznie

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        List<Order> orders = orderDbService.getALlOrders();
getALlOrders na getAllOrders

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return ResponseEntity.ok().build();
ja używam ResponseEntity.ok(null) :)

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/service/OrderDbService.java
> +    @Autowired
Nie potrzebujesz

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public ResponseEntity<OrderDto> updateOrder(@RequestBody OrderDto orderDto) {
Dla update wydaje mi się, że byłby :)

2022-11-03 19:56 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public ResponseEntity<OrderDto> updateOrder(@RequestBody OrderDto orderDto) {
Bo wiesz co aktualizowałeś za to przy create nie znasz id :D

2022-11-03 21:02 UTC, shinzu94 approved these changes

2022-11-06 16:05 UTC, shinzu94 requested changes

2022-11-06 16:05 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        orderDbService.saveOrder(order);
Nie zwróciłem  na to uwagi, ale większość tej metody powinna być w OrderService

2022-11-06 16:05 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        orderDbService.saveOrder(order);
Nie zwróciłem na to uwagi, ale większość tej metody powinna być w OrderService

2022-11-06 17:42 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return ResponseEntity.ok(orderMapper.mapToOrderDto(saveOrder));
Technicznie nie potrzebujesz żadnej zmiennej tu tworzyć

Bo mógłbyś takiego potworka zrobić
```
ResponseEntity.ok(orderMapper.mapToOrderDto(orderDbService.saveOrder(orderMapper.mapToOrder(orderDto))));
```

albo trochę lepszego potworka
```
        ResponseEntity.ok(
                orderMapper.mapToOrderDto(
                        orderDbService.saveOrder(
                                orderMapper.mapToOrder(orderDto)
                        )
                )
        );
```

No ale tutaj trochę za dujżo tego i nie czytelne już by było @matnow138 @Damian1457

2022-11-06 18:22 UTC, matnow138 approved these changes

2022-11-09 21:19 UTC, shinzu94 approved these changes

2022-11-10 19:37 UTC, matnow138 commented
rozwiąż konflikty z main

2022-11-11 19:05 UTC, shinzu94 requested changes

2022-11-11 19:05 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/repository/OrderDao.java
> +@Repository
To nie jest ci tu potrzebne :)

2022-11-11 19:44 UTC, shinzu94 requested changes

2022-11-11 19:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private BigDecimal value;
Fajnie by było jak by to dto miało id-ki usera i koszyka

2022-11-11 19:44 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +                .value(orderDto.getValue())
Fajnie by było jak by ten mapper mapował też idki usera i cart-a

2022-11-13 10:22 UTC, shinzu94 requested changes

2022-11-13 10:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private Cart cartId;
Jeśli już to CartDto, ale mówiłem o id więc Long :)

2022-11-13 10:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private User user;
Jeśli już to UserDto, ale mówiłem o id więc Long :)

2022-11-13 10:22 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    private Cart cartId;
nazwałbym to cart( ze względu na spasowanie z innymi dto, bo w takiej sytuacji cartId generealnie było by lepsze)

2022-11-14 21:06 UTC, Coriv commented on src/main/java/com/kodilla/ecommercee/OrderController.java
>      public List<OrderDto> getOrders() {
Tu powinno być Tu powinno być ResponseEntity<List<OrderDto>>

2022-11-14 21:07 UTC, Coriv commented on src/main/java/com/kodilla/ecommercee/OrderController.java
>      }
return ResponseEntity.ok(oorderMapper.mapToOrderDtoList(orders));

2022-11-14 21:10 UTC, Coriv commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public ResponseEntity<Void> createOrder(@RequestBody OrderDto orderDto) throws UserNotFoundException {
W metodzie post przynajmniej w innym kontrolerach zwracamy typem jest Dto obiektu, w tym przypadku byłoby to OrderDto zamiast Void

2022-11-14 21:23 UTC, Coriv requested changes

2022-11-14 21:23 UTC, Coriv commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return ResponseEntity.ok(null);
Można dodać do 32 linijki zmienna Order savedOrder = orderDbService.saveOrder(order);

return ResponseEntity.ok(orderMapper.mapToOrderDto(savedOrder));

2022-11-14 21:27 UTC, Coriv approved these changes

2022-11-14 21:37 UTC, shinzu94 approved these changes

2022-11-14 21:38 UTC, merged