Jdp221101 13
piotr-grosicki/project-jdp-2211-01 pull request #23
Opened 2022-11-03 10:26 UTC by KrzysiekBlaszczyk

Encja group

2022-11-03 14:48 UTC, shinzu94 requested changes
Zrób reabese/merge z main-em.

Masz 2 błędy którte powodują, że struktura się nie doda.

Musisz dodać GroupDao

2022-11-03 14:48 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/entities/Group.java
> +            fetch = FetchType.EAGER
`FetchType.LAZY`

2022-11-03 14:48 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/entities/Group.java
> +            targetEntity = Product.class,
Nie potrzebne

2022-11-03 14:48 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/entities/Group.java
> +    private long id;
`Long`

2022-11-03 14:48 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/entities/Group.java
> +            fetch = FetchType.EAGER
Brak zdefiniowanego zachowania dla kaskady

2022-11-06 16:20 UTC, shinzu94 requested changes
Dalej nie będzie się odpalać :D

2022-11-06 16:20 UTC, shinzu94 commented on src/main/java/com/kodilla/ecommercee/entities/Group.java
> +            cascade = CascadeType.ALL,
raczej CascadeType.PERSIST ze względu na to, że usunięci grupy nie powinno usuwać produktów

2022-11-09 20:49 UTC, shinzu94 approved these changes

2022-11-09 20:49 UTC, Damian1457 approved these changes

2022-11-09 21:13 UTC, merged