Order Entity tests
piotr-grosicki/project-jdp-2211-01 pull request #24
Opened 2022-11-04 18:59 UTC by pawelkrzywda

2022-11-04 20:22 UTC, matnow138 commented
wrzuciłem uwagi do pierwszego testu. Wszystkie te uwagi powtarzają się przez kolejne testy.

2022-11-04 20:28 UTC, matnow138 requested changes

2022-11-04 20:28 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +    private OrderDao orderDao;
dlaczego nie wywołujesz UserDao i CartDao?

2022-11-04 20:28 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +                .cartId(cart1)
Dlaczego chcesz przypisać na sztywno tą zmienną? Ona chyba nie powinna być w builderze.

2022-11-04 20:28 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +
Dodajesz do usera, ale nigdzie nie zapisujesz do bazy tego.

2022-11-04 20:28 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        orderDao.deleteAll();
musisz usunąć osobno wszystko.

2022-11-07 17:20 UTC, shinzu94 requested changes
W pierszej kolejności rzeczy pewne.

1. Masz konfikty więc musisz zrobić merge, rebase
2. Nie powinno być sytacji w której usuwasz kaskadowo inne encje, co z jednej strony powoduje, że powinieneś testować czy się nie usuwa kaskadowo ( i czy się dodaje kaskadowo jeśli tak się ma dziać) oraz powinieneś zmienić encje tak, żeby kaskady były inaczej zdefiniowane
3. Całkiem sporo nowych obiektów mógłbyś wytwarzać w funkcji prywatnej i było by znacznie mniej kodu i było byh czytelniej uwzględniając fakt, że te obekty nie mają dla ciebie znacznie w konkretnych testach.
4. Nie robisz odzielnej sekcji clean
5. Moim zdaniem testy create i delete może być w ramach innych testów, bo co byś nie robłł w każdym teście i tak testujesz używasz i delete (ten punkt jest berdziej kontrowersyjny niż poprzednie)

2022-11-07 20:10 UTC, matnow138 commented
1. Czy nie byłoby wygodniej tworzyć usera / cart / order BeforeEach? poprawiłoby to znacznie czytelność kodu..
2. Rozwiąż konflikty z main.
3. Czy masz w encjach CascadeType.PERSIST?
4. Tak jak Oskar napisał - nie masz osobno //Cleanup

2022-11-09 19:20 UTC, matnow138 requested changes
1. Jeśli masz zrobione powiązanie między encjami, to nie musisz wszystkiego zapisywać osobno - ważne, żebyś zapisał encję, w której tworzysz powiązanie(czyli np. dodajesz do Usera Cart i Order - wtedy zapisujesz Usera.
2. Dodałem komentarze w treści kodu - jeśli coś się powtarzało, to już nie pisałem kolejnego komentarza.

2022-11-09 19:20 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        }
Dlaczego w ten sposób? testy nie powinny zwracać informacji tekstowych.

2022-11-09 19:20 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        assertEquals(BigDecimal.valueOf(300.15),orderDao.findById(updatedOrder.getOrderId()).get().getValue());
proponowałbym rozbić to na 2 linijki kodu i zabezpieczyć Optional. Staraj się unikać .get() przy optionalu bo to prosi się o błędy.

2022-11-10 19:41 UTC, matnow138 commented
Jeśli Oskar zaakceptuje Ci .get() to jak dla mnie wtedy też będzie ok.

2022-11-11 19:03 UTC, shinzu94 requested changes
Już prawie :)

2022-11-11 19:03 UTC, shinzu94 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        Cart cart = new Cart();
Daj cart na góre

2022-11-11 19:03 UTC, shinzu94 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        assertEquals(2, orderDao.findAll().size());
Dalej nie sprawdczasz

2022-11-11 19:03 UTC, shinzu94 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +    @Test
@Transactional

2022-11-11 19:03 UTC, shinzu94 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +    @Test
@Transactional

2022-11-11 19:03 UTC, shinzu94 commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +    @Test
@Transactional

2022-11-11 20:50 UTC, pawelkrzywda commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        cartDao.save(cart2);
To już poprawiłem w ostatnim commicie

2022-11-11 20:51 UTC, pawelkrzywda commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        user2.getOrderId().add(order2);
Również poprawione w ostatnim commicie

2022-11-11 20:51 UTC, pawelkrzywda commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        user1.getOrderId().add(order1);
Już poprawione

2022-11-11 21:08 UTC, pawelkrzywda commented on src/test/java/com/kodilla/ecommercee/dao/OrderTestSuite.java
> +        int number = random.nextInt();
Zmniejszyłem teraz to ryzyko, wydaje mi się że znacząco

2022-11-11 21:16 UTC, pawelkrzywda commented
Kod poprawiony zgodnie z uwagami

2022-11-11 22:45 UTC, matnow138 approved these changes

2022-11-12 12:33 UTC, shinzu94 approved these changes

2022-11-12 19:33 UTC, merged