Feature/jdp221101 22 group controller
piotr-grosicki/project-jdp-2211-01 pull request #27
Opened 2022-11-06 15:50 UTC by shinzu94

2022-11-11 09:07 UTC, Damian1457 approved these changes

2022-11-12 08:49 UTC, pawelkrzywda commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +    private final ProductMapper productMapper;
Czy to jest potrzebne? Nie używasz tego potem w kodzie.

2022-11-12 08:54 UTC, pawelkrzywda requested changes
Brakuje mi tu metody deleteGroup(), konflikty do rozwiązania.

2022-11-13 18:06 UTC, pawelkrzywda approved these changes

2022-11-13 18:28 UTC, KrzysiekBlaszczyk approved these changes
jak dla mnie ok

2022-11-13 19:09 UTC, merged