Jdp221101 17 product entity tests
piotr-grosicki/project-jdp-2211-01 pull request #30
Opened 2022-11-09 09:33 UTC by Coriv

2022-11-09 19:58 UTC, matnow138 requested changes
1.  dlaczego zmieniasz gradle?
2.  Czy zrobileś merge/rebase z mainem? to wygląda tak jakbyś miał stare pliki i chciał je wrzucić do maina.

2022-11-09 20:06 UTC, matnow138 reviewed
.

2022-11-09 20:14 UTC, matnow138 requested changes
Dodałem komentarze w kodzie.

2022-11-09 20:14 UTC, matnow138 commented on src/main/java/com/kodilla/ecommercee/entity/Group.java
> +   // @NotNull
czy ten komentarz jest tutaj konieczny?

2022-11-09 20:14 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +        */
Czy ten komentarz musi tutaj być? wygląda jak część kodu, który zapomniałeś usunąć.

2022-11-09 20:14 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +                .group(group)
czy nie lepiej zrobić powiązanie nie będące częścią buildera?

2022-11-09 20:14 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +        System.out.println(productDb.get());
wywoływanie .get() prosi się o problem. Dodatkowo - testy nie powinny raczej zwracać wartości tekstowych.

2022-11-09 20:14 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +        System.out.println(productDb.get().getDescription());
j.w.

2022-11-09 20:14 UTC, matnow138 commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +        //cartDao.deleteById(cart.getCartId());
Dlaczego nie czyścisz? nie masz też sekcji //cleanup

2022-11-09 20:15 UTC, matnow138 requested changes
Czy masz tutaj aktualne pliki z main?

2022-11-10 08:51 UTC, Coriv commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +        //cartDao.deleteById(cart.getCartId());
Hm, to było zakomentowane w pierwszym commicie w którym zgłaszałem ze mam problemy z działaniem testów, w najnowszym jest już sekcja cleanup

2022-11-10 08:52 UTC, Coriv commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +        System.out.println(productDb.get());
tego tez już nie było w moim commicie który dałem do cr

2022-11-10 08:52 UTC, Coriv commented on src/test/java/com/kodilla/ecommercee/dao/ProductTestSuite.java
> +                .group(group)
Czy to ma jakiekolwiek znaczenie ?

2022-11-10 08:54 UTC, Coriv commented on src/main/java/com/kodilla/ecommercee/entity/Group.java
> +   // @NotNull
Zakomentowalem te część bo tylko wtedy encją która testowałem przechodziła testy, a w momencie gdy wysyłałem ten commit encja Group jeszcze nie miała finalnej implementacji, tylko stworzona przez kogoś żeby nie blokować prac. .

2022-11-10 19:26 UTC, matnow138 approved these changes

2022-11-11 09:06 UTC, Damian1457 approved these changes

2022-11-11 09:57 UTC, merged