Adding swagger
piotr-grosicki/project-jdp-2211-01 pull request #32
Opened 2022-11-10 20:55 UTC by matnow138

2022-11-11 19:51 UTC, shinzu94 requested changes
Nie skonfigutowałeś, żeby nie było [basic-error-controller](http://localhost:8080/swagger-ui.html#/basic-error-controller)

a swoją drogą fajnie by było też skonfigurowąc ścierzke na której będzie to wyświetlane

2022-11-12 09:01 UTC, pawelkrzywda approved these changes

2022-11-12 09:01 UTC, pawelkrzywda commented
jeden konflikt do rozwiązania

2022-11-12 12:30 UTC, shinzu94 approved these changes
Ok rozwiąż konflikty i możesz mergować

2022-11-12 20:40 UTC, merged