Adding UserDto and Controllers
piotr-grosicki/project-jdp-2211-01 pull request #6
Opened 2022-10-23 19:52 UTC by matnow138

2022-10-24 07:09 UTC, piotr-grosicki requested changes

2022-10-24 07:09 UTC, piotr-grosicki commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
dlaczego taka zmiana?

2022-10-24 07:09 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PatchMapping(value = "/{userID/blockUser")
brakuje jednej klamerki

2022-10-24 07:09 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public boolean blockUser(@PathVariable int userID, boolean isActive) {
ten parametr is active nie zadziala w controllerze

2022-10-24 07:09 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +
niepoprawne formatowanie

2022-10-24 07:09 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/UserDto.java
> +    private int id;
id to raczej long

2022-10-24 17:18 UTC, matnow138 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
IntelliJ nie pozwalało mi skompilować programu przy wersji Gradle 4.10.2

2022-10-24 18:04 UTC, matnow138 commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Mój IntelliJ nie pozwalał zbudować projektu przy tej wersji gradle. Zrobiłem downgrade Javy i już działa.

2022-10-25 08:44 UTC, piotr-grosicki requested changes
mimo zbicia wersji wrappera, nadal go aktualizujesz, spojrz na zmienione pliki w tym PR

2022-10-25 08:55 UTC, matnow138 commented
Czy teraz będzie ok?

2022-10-26 06:33 UTC, piotr-grosicki commented
> Czy teraz będzie ok?

no nie, teraz usuwasz calego wrappera dla wszystkich :)

2022-10-27 17:32 UTC, closed without merging